export const artworks = [
  {
    id: 1,
    title: "VOCES",
    year: "2020",
    technique: "Acuarela sobre papel",
    dimensions: "39 X 20.2 CM",
    description:
      "“CUANDO VIVIR ES UNA MIERDA, SUICIDARSE ES UN DERECHO” Y ASÍ EMPIEZA LA NARRATIVA DONDE UN NIÑO SE CREE EL REY DEL MUNDO MIENTRAS LA BOLSA DE PEGANTE LO CONSUME, ESTOS SON NORMALMENTE PENSAMIENTOS Y SENSACIONES QUE EMANAN DE AQUELLA MIRADA, DONDE LAS VOCES DE SU CABEZA Y LA SOCIEDAD, SOLO LO VEN COMO UN PARÁSITO QUE POCO A POCO SE VA DESVANECIENDO DE ESTA SOCIEDAD.",
    image: "https://ik.imagekit.io/hi0ocsyfm/voces.png?updatedAt=1754362937487",
  },
  {
    id: 2,
    title: "IQ-1",
    year: "2021",
    technique: "Técnica mixta",
    dimensions: "22.3 X 15.3 CM",
    description:
      "MIENTRAS EL PAÍS PIDE A GRITOS JUSTICIA FRENTE AL ATAQUE DE SUS DERECHOS, EL TÍTERE Y SU DICTADOR CELEBRAN UN PARTIDO DE FÚTBOL, FESTEJAN UN FALSO TÍTULO Y SE HACE LLAMAR PRESIDENTE MIENTRAS LO ÚNICO QUE SALE DE SU BOCA ES EL CUENTO DE BLANCA NIEVES Y LOS SIETE ENANITOS, NO NOS REPRESENTA ALGUIEN QUE TIENE PENSAMIENTOS BÁSICOS Y SE HUMILLA SOLO.",
    image: "https://ik.imagekit.io/hi0ocsyfm/iq-1.png?updatedAt=1754362880112",
  },
  {
    id: 3,
    title: "NO NAME",
    year: "2022",
    technique: "Acrílico sobre acetato",
    dimensions: "25 X 20 CM",
    description:
      "CONDENADOS AQUELLOS QUE SON ESCLAVOS DE SUS PROPIOS PREJUICIOS, SIN NINGUNA LIBERTAD CONDICIONADA, DONDE LAS MADRES LLORAN AGONÍAS.",
    image: "https://ik.imagekit.io/hi0ocsyfm/image.png?updatedAt=1754362768474",
  },
  {
    id: 4,
    title: "FLYING FISHES",
    year: "2023",
    technique: "Óleo sobre tela",
    dimensions: "60 X 50 CM",
    description:
      "SERES MARINOS QUE VUELAN Y PELEAN EN CONTRA DE LA MAREA, POR SOBREVIVENCIA, EXISTIENDO Y FLUYENDO CON EL UNIVERSO, SERES LLENOS DE LUZ QUE SON VÍCTIMAS DE NUESTRA EXISTENCIA, PERSEGUIDOS SOLO VISTOS COMO DECORACIÓN Y ALIMENTO, COLOCÁNDOLE PRECIO A SU VIDA EN UN MUNDO DONDE SE ESTÁ ESCASEANDO LA IMAGINACIÓN Y LA PRODUCCIÓN ES LA DOMINACIÓN DEL MUNDO.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03813.JPG?updatedAt=1753411592835",
  },
  {
    id: 5,
    title: "LLORÓN",
    year: "2023",
    technique: "Pigmento sobre papel acuarela",
    dimensions: "49 X 21 CM",
    description:
      "¿ACASO LLORAR Y EXPRESAR LO QUE SENTIMOS SE VOLVIÓ UN TABÚ? ESTAMOS AL BORDE DE LA LOCURA POR NO EXPRESAR LO QUE SENTIMOS, ESTAMOS LLENOS DE LLAGAS QUE NO SE HAN CURADO POR NO SANAR TODO ESO QUE NOS ATORMENTA, LOS SENTIMIENTOS NOS QUEMAN Y PIDEN A GRITOS EXPRESARSE, PERO EL AUTOCONTROL QUE NOS OBLIGARON NOS CIEGA Y NOS ENSORDECE SIN ESCAPATORIA ALGUNA.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/lloron.png?updatedAt=1754363299509",
  },
  {
    id: 6,
    title: "¿QUIÉN CONSUME?",
    year: "2022",
    technique: "Óleo sobre madera",
    dimensions: "80 x 60 CM",
    description:
      "¿ACASO NO SIENTEN QUE LO QUE COMEN LOS DEVORA?, ¿POR QUÉ? ¿QUÉ NECESIDAD HAY? ¿QUÉ TIENEN SUS ALMAS PARA CONTAR? CADA CIUDADANO DE LA CALLE TIENE SU HISTORIA, TIENE SUS ALEGRÍAS, TRISTEZAS ¿SERÁN ELLOS EL REFLEJO QUE MUESTRA EL TEMOR Y EGOÍSMO? ¡TANTAS PREGUNTAS! ¿QUIÉNES SON? ¿POR QUÉ LO SON?",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03801.JPG?updatedAt=1754354995939",
  },
  {
    id: 7,
    title: "DIXON",
    year: "2023",
    technique: "Técnica mixta",
    dimensions: "88.5 X 65 CM",
    description:
      "LA SERPIENTE, SÍMBOLO DE MIEDO EN LA VIDA DE DIXON, QUE AUMENTA CON EL ÉXTASIS DE LAS SUSTANCIAS, TERROR QUE LLEVA ESAS ALUCINACIONES A FLOR DE PIEL QUE LO ESTRANGULA Y LO ENGULLE HASTA EL FONDO DE SU SER SIN ESCAPATORIA ALGUNA.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03805.JPG?updatedAt=1754354998221",
  },
  {
    id: 8,
    title: "ALFONSO",
    year: "2023",
    technique: "Óleo sobre tela",
    dimensions: "79 X 49 CM",
    description:
      "UN SUEÑO TRASLÚCIDO PROVOCADO DE SUS ÚLTIMAS ENERGÍAS, PROPÓSITO DE QUERER OFRECER UN DULCE PARAÍSO, VESTIDO DE TELAS FINAS SIENDO TESTIGO DE SU VICTORIA DEJANDO A UN LADO EL SABOR AMARGO DE LA HEROÍNA Y LA BASURA, ESPERANDO ENTREGAR CHOCOLATES Y EL BOLETO DORADO. Y Aun ASÍ LA TENTACIÓN DE SUS BOMBONES ACARAMELADOS RELLENOS DE HEROÍNA, QUE INTENTA NO VOLVERLOS A SABOREAR, DULCE TENTACIÓN QUE HA LUCHADO DURANTE UN LARGO TIEMPO QUE SIENTE ETERNO.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03803.JPG?updatedAt=1754354998554",
  },
  {
    id: 9,
    title: "JHON EDWIN",
    year: "2023",
    technique: "Óleo sobre tela",
    dimensions: "89.5 X 59.8 CM",
    description:
      "POR SIMPLE CURIOSIDAD PASO DE SABER CÓMO SE VEÍA A CONOCER COMO SE SENTÍA, EL BASUCO, SUSTANCIA QUE PROVOCA MIEDO, ANGUSTIA Y UN GRITO DE AGONÍA QUE SIENTE EL ALMA.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03806.JPG?updatedAt=1754354996957",
  },
  {
    id: 10,
    title: "OBITUARIO",
    year: "2023",
    technique: "Óleo sobre periódico",
    dimensions: "88.1 X 58.5 CM",
    description:
      "EN LAS NOTICIAS LOS SEÑALAN DE AGRESORES, QUE SON LA RAZÓN DE QUE LA CIUDAD SE VEA DECADENTE, PERO, NO SON EXACTAMENTE ESO, SON SERES HUMANOS QUE UNOS ELIGIERON Y OTROS FUERON OBLIGADOS, ELLOS TAMBIÉN SIENTEN TRISTEZAS, ENOJOS Y ALEGRÍAS, NO SON UN CERO A LA IZQUIERDA, PUES ELLOS AL IGUAL QUE NOSOTROS SE CONSUMEN Y SON RESULTADOS DE NUESTRO EGOÍSMO.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03809.JPG?updatedAt=1754354996546",
  },
  {
    id: 11,
    title: "DULCE ACOMPAÑANTE",
    year: "2023",
    technique: "Óleo sobre costal",
    dimensions: "42 X 61.3 CM",
    description:
      "ÚNICO SER VIVIENTE QUE LOS VE COMO SON, SERES SINTIENTES PELUDITOS DE CUATRO PATAS QUE NO VEN A SUS AMOS CON OJOS DE CRÍTICA, NO VEN LA SUCIEDAD NI LA BASURA, SINO ALGUIEN A QUIEN AMAR, UN DULCE ACOMPAÑANTE DE UN NÓMADA DE LA CIUDAD.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03812.JPG?updatedAt=1753411592543",
  },
  {
    id: 12,
    title: "DON CARLOS",
    year: "2023",
    technique: "Óleo sobre tela",
    dimensions: "80.5 X 58.3 CM",
    description:
      "A PESAR DEL MUNDO TAN SALVAJE, TAN DECADENTE Y TAN VULGAR, HAY ALMAS QUE NO CAEN EN LA DEPRESIÓN Y LA ANSIEDAD DEL AMBIENTE COMO DON CARLOS QUE LLEVA DESDE LOS 8 AÑOS EN LA CALLE, Y EN SUS MÁS DE 50 AÑOS CREANDO NARRATIVAS, NUNCA DEJÓ QUE SE LLEVARÁN SU LUZ, AL CONTRARIO SU IMPACTANTE CABALLEROSIDAD PERMITE COMPARTIR Y MOSTRAR SU VIDA.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03800.JPG?updatedAt=1754354997958",
  },
  {
    id: 13,
    title: "GUAPACHA",
    year: "2023",
    technique: "Óleo sobre tela",
    dimensions: "77 X 54.6 CM",
    description:
      "UN HOMBRE QUE A PRIMERA VISTA IMPACTA, ALTO, FORNIDO, CON UNA PRESENCIA TAN FUERTE QUE MUY POCOS SE ACERCAN PARA HABLARLE POR TEMOR, PERO CUANDO UNO ROMPE ESA BARRERA, CAMBIA LA IMAGEN A UN SER PEQUEÑO CON LA EXPERIENCIA DE MILES DE VIDAS, Y UNA DE ESAS VIDAS LO HACE VULNERABLE, PORQUE SUS TEMORES SON FANTASMAS QUE OBSERVAN CON TIMIDEZ Y OSCURAS MIRADAS, ESPERANDO SU MAYOR OPORTUNIDAD PARA VOLVERLO A DEVORAR.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03798.JPG?updatedAt=1754354997830",
  },
  {
    id: 14,
    title: "ANÓNIMOS",
    year: "2023",
    technique: "Óleo sobre tela",
    dimensions: "70.3 X 50.5  CM",
    description:
      "HABITANTES DE CALLE SIN ROSTRO, VIGILADOS POR SUS TEMORES Y ADICCIONES, CUBRIÉNDOSE CON MUGRE Y BASURA PARA NO SER DETECTADOS Y ELLOS LOGRAR PERDERSE DE UN PLANO TERRENAL AL CUAL NO SIENTEN UN HOGAR, LOGRANDO ASÍ ENGAÑARNOS CON UNA IMAGEN DESHUMANIZADA DE SU SER, CUANDO EN SU INTERIOR AÚN SON IGUALES A NOSOTROS.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03797.JPG?updatedAt=1754354997726",
  },
  {
    id: 15,
    title: "CLAUSTROFOBIA",
    year: "2023",
    technique: "Óleo sobre tela",
    dimensions: "59.6 X 73.1 CM",
    description:
      "MIRADAS DESPRECIABLES DE SERES MAQUILLADOS, MIRADAS SIN VIDA, PRETENCIOSOS Y APÁTICOS, MIRADAS QUE LE TRANSMITEN SENSACIONES ASQUEROSAS, SENSACIONES DONDE EL MIEDO LES INVADE A AQUELLOS SERES HABITANTES DE CALLE Y NO ENCUENTRAN UN REFUGIO, ¿ACASO TÉ HAS PREGUNTADO CÓMO ESTÁN? O SOLO LOS MIRAS CON DESPRECIO Y ASCO. ESTAMOS ENCERRADOS EN LA MISMA CAJA DE CARTÓN SIN DARNOS CUENTA, ABSOLUTAMENTE NADIE DEBE DE SENTIRSE SUPERIOR A NADIE, ELLOS NO SON DIFERENTES, RÍEN, LLORAN, SUFREN, TIENEN UN PASADO Y LUCHAN CON SUS DEMONIOS ¿TÚ TAMBIÉN RÍES? ¿TÚ TAMBIÉN LLORAS? ¿TÚ NO LUCHAS CON TUS DEMONIOS? ¿ENTONCES? ¿POR QUÉ NO LO ACEPTAS? ¿POR QUÉ SOLO JUZGAR? ¿PREJUICIOS O MIEDOS?",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC03799.JPG?updatedAt=1754354998626",
  },
  {
    id: 16,
    title: "AUTOVORAREFILIA",
    year: "2024",
    technique: "Óleo sobre tela",
    dimensions: "50.8 X 70.8 CM",
    description:
      "DESEOS INSACIABLES FANTASEANDO A CADA MOMENTO, SUCCIONANDO MIS PROPIAS TRIPAS, CADA DÍA ME ALIMENTO CON HIERBAS FINAS PARA TENER EL MEJOR SABOR, UN SABOR QUE NI EN EL RESTAURANTE MÁS FINO DEL MUNDO HAZ PROBADO, SOY UN PLATO EXQUISITO, UN PLATO QUE NI EL MEJOR CHEF DEL MUNDO PODRÍA CREAR, Y ESTA SOY YO EXCITÁNDOME CON EL SABOR DE MI PROPIA CARNE.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/WhatsApp%20Image%202024-10-23%20at%201.01.00%20PM%20(1).jpeg?updatedAt=1753411410532",
  },
  {
    id: 17,
    title: "RAÍCES DEL REY",
    year: "2024",
    technique: "Óleo sobre tela",
    dimensions: "28.5 X 29 CM",
    description:
      "UNA DE MIS NARRATIVAS FAVORITAS SOBRE JABÓN REY HA SIDO PODER CREAR UN RELATO LLENO DE MAGIA, DONDE NUESTRAS ABUELAS NOS RECOMIENDAN BAÑARSE CON EL EN UN RIO COMO RITUAL DE PURIFICACIÓN, COMO TAMBIÉN SER LA PRIMERA OPCIÓN PARA LAVAR LA ROPA Y SI ES POSIBLE TODA LA CASA. CADA OBJETO HA SIDO ESCOGIDO CUIDADOSAMENTE, EL TAMBOR COMO SÍMBOLO DE ESAS MADRES DONDE EN SUS TIEMPOS LIBRES BORDABAN TODO TIPO DE HISTORIAS O DECORACIONES PARA SUS HOGARES, UN ÁRBOL GENEALÓGICO PASANDO CADA RITUAL, CADA SECRETO Y CONOCIMIENTO SOBRE EL MISMO, Y UN BARCO DE PAPEL COMO SÍMBOLO DE ESPERANZA PARA LAS SIGUIENTES GENERACIONES QUE JABÓN REY NUNCA ABANDONARA Y SEGUIRÁ EN LOS HOGARES.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/DSC08388.JPG?updatedAt=1754354984292",
  },
  {
    id: 18,
    title: "EMPATÍA",
    year: "2024",
    technique: "Acrílico sobre lienzo",
    dimensions: "21x14 CM",
    description:
      "NO IMPORTA CUÁN SONRIENTE SEAS, CUÁN ESTABLE APARENTES TU VIDA, SIEMPRE HAY ALGO QUE TE QUITA EL ALIENTO, DEJA DE MENTIRTE QUE LA VIDA ES COLOR DE ROSA Y ACEPTA TU OSCURIDAD, PUES PERTENECE A TI DESDE QUE NACISTE Y NO DEJARÁ DE SEGUIRTE SIMPLEMENTE PORQUE LA IGNORES, RECONÓCELA, ELLA TAMBIÉN HACE PARTE DE TU VIDA Y AUNQUE LE TENGAS MIEDO, SOLAMENTE NECESITA SER ENTENDIDA Y HACERLA PARTE DE TU VIDA PARA QUE COEXISTAN Y ASÍ TENGAN UNA VIDA MÁS TRANQUILA, PUES RECUERDA, NO HAY LUZ SIN OSCURIDAD.",
    image:
      "https://ik.imagekit.io/hi0ocsyfm/IMG-20250626-WA0137.jpg?updatedAt=1753412186890",
  },
  {
    id: 19,
    title: "AUNQUE EL SOL LLORE",
    year: "2024",
    technique: "Acrílico sobre papel",
    dimensions: "50x70 CM",
    description: "Y HOY EL SOL TRAGÓ TAN FUERTE QUE AQUELLAS NUBES QUE LO TAPABAN LLORARON LO QUE ÉL ESCONDÍA EN SU INTERIOR, HOY EL SOL VIO CÓMO SU AMADA LUNA REGOCIJABA DEL CALOR DE UNA ESTRELLA AJENA AL MUNDO QUE CONSTRUYERON Y DANZARON DIFERENTE, HOY EL SOL YA NO ESTÁ ACOMPAÑADO DE LUNA, PUES SÓLO VE EN EL FIRMAMENTO POLVO DE LO QUE SINTIÓ UN AMOR ETERNO, AQUEL SOL, MIRA EN LAS CALMAS AGUAS SU REFLEJO, CASI SOMBRÍO, PUES AQUELLA NOCHE DECIDIÓ APAGARSE UN POCO MÁS.",
    image: "https://ik.imagekit.io/hi0ocsyfm/sol.png?updatedAt=1754363224464",
  },
  {
    id: 20,
    title: "PARASITO",
    year: "2024",
    technique: "Acrílico sobre lienzo",
    dimensions: "25x35 CM",
    description: "CUANDO EL SER HUMANO APRENDE QUE LO MEJOR PARA SUS VIDAS ES NO HABLAR DE LO QUE SIENTE, CRECE EN NUESTRA GARGANTA UN PARÁSITO QUE CONDUCE TODO LO QUE PENSAMOS DESDE LA CABEZA HASTA EL CUELLO CON LA INTENCIÓN DE APODERARSE DE NUESTRO SER HASTA EL PUNTO DE NO PERMITIR EL PASO DE OXÍGENO, MATÁNDONOS LENTAMENTE, CON UN DAÑO COLATERAL A NUESTRA ALMA, CONSUMIENDO NUESTRA ENERGÍA PARA ALIMENTARSE AÚN MÁS, ABSORBIENDO NUESTRA LUZ, CONTROLANDO TODO A TRAVÉS DE UNA FALSA ILUSIÓN DONDE MOSTRAMOS UNA SONRISA VACÍA, PERO AL FINAL, NOS QUITA TODO Y LO QUE DEJA DENTRO DE NOSOTROS ES UN PENSAMIENTO PARA ENAMORARNOS DE LA MUERTE Y BUSCARLA COMO ACTO FINAL DE ESTE PARÁSITO.",
    image: "https://ik.imagekit.io/hi0ocsyfm/sombrero.png?updatedAt=1754364788177",
  },
];
